[general]
import = [
    "~/.config/alacritty/themes/nightfox.toml"
]

[window]
decorations = "None"
padding = { x = 7, y = 7 }

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
size = 13
