# NOTEBOOK SETTINGS
[notebook]
dir = "~/notebooks/personal"

# NOTE SETTINGS
[note]

# The default title used for new note, if no `--title` flag is provided.
default-title = "Untitled"

# Template used to generate a note's filename, without extension.
filename = "{{id}}"

# Template used to generate a note's content.
# If not an absolute path, it is relative to .zk/templates/
template = "default.md"

# Configure random ID generation.

# The charset used for random IDs.
id-charset = "hex"

# Length of the generated IDs.
id-length = 8

# Letter case for the random IDs.
id-case = "lower"


# MARKDOWN SETTINGS
[format.markdown]

# Enable support for #hashtags
hashtags = true


# EXTERNAL TOOLS
[tool]

# Default editor used to open notes.
editor = "nvim"

# Default shell used by aliases and commands.
shell = "/bin/bash"

# Pager used to scroll through long output.
pager = "less -FIRX"

# Command used to preview a note during interactive fzf mode.
fzf-preview = "bat -p --color always {-1}"
fzf-line = "{{style 'blue' rel-path}}{{#each tags}} #{{this}}{{/each}} {{style 'black' body}}"


# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"


# COMMAND ALIASES
[alias]

# Edit the last modified note.
edlast = "zk edit --limit 1 --sort modified- $@"

# Edit the notes selected interactively among the notes created the last two weeks.
recent = "zk edit --sort created- --created-after 'last two weeks' --interactive"

# Show a random note.
lucky = "zk list --quiet --format full --sort random --limit 1"

# Create a note from a free title
nt = 'zk new --title "$*"'

# Print and sort the word count of selected notes
wc = "zk list --format '{{word-count}}\t{{title}}' --sort word-count $@"

# Remove a note selected with fzf.
rm = 'zk list --interactive --quiet --format "{{abs-path}}" --delimiter0 $@ | xargs -p0 rm -vf --'

# LSP (EDITOR INTEGRATION)
[lsp]

[lsp.diagnostics]

# Warn for dead links between notes.
dead-link = "error"
